Makefile, requirements-dev.in, requirements-dev.txt, requirements.in, requirements.txt, setup.cfg, src/secretbox/loadenv.py, tests/aws_test.py, tox.ini
- Do not require the boto3 library for standard module install
- Tests continue to require boto3 library
- Tests cover conditional of boto3 not being installed
- `load_aws_store()` raises `NotImplementedError` directing to install boto3
- `load()` silently skips call to aws loader
- Refactor of test code
=> boto3 secrets manager methods to optional dependencies

src/secretbox/loadenv.py, tests/aws_test.py, tests/conftest.py, tests/loadenv_test.py
Due to manipulating `os.environ` within the testing fixtures, there were side-effects bleeding into adjacent tests.  This branch does not change functionality.  However, it does heavily refactor tests to remove side-effect bleeding.
=> Remove side-effects within tests

README.md, requirements-dev.txt, src/secretbox/secretbox.py, tests/aws_test.py, tests/conftest.py
closes #12 
Adds:
`AWS_SSTORE_NAME` and `AWS_REGION_NAME` are pulled from existing environ variables if set when the class instance is created.  The keyword arguments for these values remains priority and will be used if provided.
Changes:
Class API: keyword argument `aws_region` renamed to `aws_region_name` for consistency 
This will allow the secret store location and name to be packaged in the deployment container/target as environment values and reduce the amount of values hardcoded.
=> Aws enhancements

src/secretbox/secretbox.py
This prevents the `load_aws()` call during `load()` or `auto_load=True`
if the values are empty or missing. In cases that boto3 is installed but
the secret store is not being used this will reduce load time.
closes #14
=> Do not run load_aws if values are empty or None

src/secretbox/secretbox.py
Slipped my attention that the parameter was given a leading underscore
instead of a trailing one.  Private parameters don't make sense.
Closes #15
=> Rename parameter _in to in_

tests/aws_test.py
With an additional logic check to increase load times when boto3 is
available but no aws values are present we skipped testing edge cases.
This adjusts the test to directly call the loading methods, ensuring
even with initial logic we are handing edge cases in the internal
methods.
=> Adjust test for coverage

.pre-commit-config.yaml, src/secretbox/secretbox.py, tests/secretbox_test.py
Add `debug_flag` parameter for creating an instance of Secretbox. This
enables the class logger to `DEBUG` levels (normally `ERROR`). Any
output with values of loaded variables is truncated, only showing the
last one-fourth of the value.
Additionally, add E203 to `flake8` ignore list because we aren't going
to fight `black` for who is correct on where the `:` goes in a list
splice.
=> Add debug logging, optional flag

README.md, src/secretbox/secretbox.py, tests/secretbox_test.py
Move away from fall-through patterns for `.get`, `.get_int`, and
`.get_list` methods.  These methods will now raise errors if the key is
not found and no default is given.
Adjusted `SecretBox` init parameters to be keyword only.
Small internal adjustment to how keyword dicts are merged.
=> Implement code review suggestions

README.md, setup.cfg, src/secretbox/envfile_loader.py, tests/conftest.py
This change allows, and strips, the `export` keyword from a loaded
`.env` file's key. This should allow the `.env` file to be loaded into
the environment from the shell and from SecretBox.
=> `.env` parsing update

setup.cfg, src/secretbox/awssecret_loader.py, tests/awssecret_loader_test.py, tests/conftest.py
botocore.parsers will display the entire response body in a `DEBUG`
level log. As this can include secrets/tokens that we do not want in
console output (or cloudwatch) we add a filter to `botocore.parsers` and
redact the secrets. This filter is removed in a `finally` block,
hopefully leaving the enviornment unpolluted.
closes #44
=> Filter response body from botocore parsers

tests/awsparameterstore_loader_test.py, tests/awssecret_loader_test.py, tests/conftest.py, tests/envfile_loader_test.py, tests/environ_loader_test.py, tests/secretbox_test.py
These changes move most of the contents of `conftest.py` into the appropriate testing module. It also removes the `scope="function"` and `name=[name]` parameters of the `@pytest.fixture` decorator as these are the default behavior of the decorator. Now that secretbox has been refactored into loaders, it no longer makes sense to hold loader specific fixtures in the `conftest.py` file.
3afd9c6 conftest cleanup
779130e awsparameterstore_loader test cleanup
6180208 awssecret_loader test cleanup
688807a secretbox tests cleanup
a7f62d8 envrion_loader cleanup
0c974be envfile_loader clean up
=> Test cleanup

src/secretbox/awsparameterstore_loader.py, src/secretbox/awssecret_loader.py, tests/awsparameterstore_loader_test.py, tests/awssecret_loader_test.py
Adds more forgiving import requirements for deployments to AWS lambdas. Enhances logging in parameter store loader to focus on `ClientError`.
0d80b24 Allow `boto3-stubs` to be optional for parameter store
82d1abb Allow `boto3-stubs` to be optional for secretmanager
=> Softer import conditions and logging enhancements

src/secretbox/aws_loader.py, src/secretbox/awsparameterstore_loader.py, src/secretbox/awssecret_loader.py, tests/aws_loader_test.py, tests/awsparameterstore_loader_test.py, tests/awssecret_loader_test.py
This change moves all mutual classes used by secrets manager loader and
parameter store loader into a superclass to be used by both. This
simplifies testing and sharing of methods.
4b9d110 Restore test: incorrectly removed
b6edba2 Remove duplicate tests with refactor
b436ac9 Refactor to use new aws_loader superclass
7793d7a Refactor mutual methods into superclass for AWS loaders
=> Refactor AWS loaders

src/secretbox/aws_loader.py
botocore uses a custom object `botocore.awsrequest.HeadersDict` for
logging. This was missed in testing and is now corrected.
=> Correct logging filter

tests/awssecret_loader_test.py, tests/conftest.py
No API changes, only test changes.  Begins work of #57 
a2102c9 Remove moto testing framework, replace with botocore Stubber
1c83ddd Auto use AWS cred masking fixture
=> Remove moto testing framework, replace with botocore Stubber

tests/awsparameterstore_loader_base_test.py, tests/awsparameterstore_loader_test.py, tests/awssecret_loader_base_test.py, tests/awssecret_loader_test.py, tox.ini
closes #63 
Remove the `importlib` calls which simulated `boto3` and `mypy_boto3_...` missing from the installed library. Replace with split tests that are run with a basic install, then with a full optional install `[aws]`.
=> Remove importlib from tests

src/secretbox/aws_loader.py, src/secretbox/awsparameterstore_loader.py, src/secretbox/awssecret_loader.py, tests/aws_loader_test.py
This change prevents any boto3 debug logging by default in secretbox. This is a change from the previous filter which specifically targeted `botocore.parse` and removed sensitive data pulled from secret store or parameter store.  With this change, logging level of `INFO` (20) is enforced when a boto3 call is made.
This can be disabled by flipping the `hide_boto_debug` class variable to `False` for either of the two AWS handlers. Note, this should never be done in production as boto3 modules will log, in plain text, your secrets and the bearer secrets that boto3 is using for AWS requests.
closes #77
=> Prevent Boto3 debug logging

src/secretbox/awssecret_loader.py, tests/awssecret_loader_test.py
This change allows a plain string to be stored in secret manager. We use the
secret name as the key in this situation and the string as the value.
closes #70
=> Accept plain-string in secret manager, use secret name as key

README.md, src/secretbox/secretbox.py, tests/secretbox_test.py
This change introduces the `.set()` method for `SecretBox`. Allows the injection of secrets to `SecretBox` and the environment at a code level.
=> Preocts 20220620 add set method

src/secretbox/envfile_loader.py
This proposal simplified the existing 2 function calls and conditional statements by using a single compiled regex argument. It should improve performance and simplify future usage.
```regex
([\"'])(.*)\1$|^(.*)$
```
> This matches for surrounding single or double quotes, but only if at the beginning and end of the text, and only if both types match. This is logically equivalent to the original implementation.
```py
import re
test_1 = [
"Text isn't there.",
"\"Text isn't there.\"",
"'Text isn't there.'",
]
test_2 = [
"'Text isn't there.",
"Text isn't there.'",
"\"Text isn't there.'",
"Text isn't there.'\"",
]
RE_LTQUOTES = re.compile(r"([\"'])(.*)\1$|^(.*)$")
def remove_lt_quotes(in_: str) -> str:
"""Removes matched leading and trailing single / double quotes"""
m = RE_LTQUOTES.match(in_) …
```
=> Simplified surrounding quote removal regex

.pre-commit-config.yaml, README.md, pyproject.toml, src/secretbox/py.typed, src/secretbox/secretbox.py, tests/secretbox_test.py
This change pulls references to the available loaders into the `SecretBox` class for qol.
- Removed `get_int()`, `get_list()`
Also add the `py.typed` file to the module.
=> Clean up secretbox class, mypy improvements

src/secretbox/aws_loader.py, src/secretbox/awsparameterstore_loader.py, tests/aws_loader_test.py
Cleaner, easier way to suppress the output of `boto3` and `botocore` libraries that will dump your AWS auth token and plain-text parameter secrets to the logs.
closes #92
=> Preocts 20220727

README.md, src/secretbox/aws_loader.py, src/secretbox/awsparameterstore_loader.py, src/secretbox/awssecret_loader.py, src/secretbox/exceptions.py, tests/aws_loader_test.py, tests/awsparameterstore_loader_test.py, tests/awssecret_loader_base_test.py, tests/awssecret_loader_test.py
This change reduces the number of branches that need to be tested by
removing the try/catch branches from the loads. Instead a single
try/catch is used at the `run()` method and the exceptions are either
squashed or bubble up, depending on an argument of the loader.
The default behavior of `secretbox` is maintained: Exceptions are squashed
by default.
=> Refactor AWS loaders for handling exceptions

tests/aws_loader_test.py, tests/awsparameterstore_loader_test.py, tests/awssecret_loader_test.py
This change moves two tests into the `aws_loader` to test the `run` method directly instead of testing it indirectly via the separate modules.  We also completely test `log_aws_error` method now that the loaders are not catching exceptions themselves.
=> Correct tests after refactors

.pre-commit-config.yaml, src/secretbox/aws_loader.py, src/secretbox/awsparameterstore_loader.py, src/secretbox/awssecret_loader.py, src/secretbox/envfile_loader.py, src/secretbox/environ_loader.py, src/secretbox/exceptions.py, src/secretbox/secretbox.py, tests/aws_loader_test.py, tests/awsparameterstore_loader_base_test.py, tests/awsparameterstore_loader_test.py, tests/awssecret_loader_base_test.py, tests/awssecret_loader_test.py, tests/conftest.py, tests/envfile_loader_test.py, tests/environ_loader_test.py, tests/secretbox_test.py
black 24.1 formatting changes
Do to conflicts against the format of `black`, the tool `reorder-python-imports` is replaced with `isort`.
Removing `pyupgrade` to reduce tool opinionation further.
=> pre-commit updates with formatting changes

src/secretbox/secretbox.py, tests/secretbox_test.py
A complete rewrite of the library from the ground up. The prior
mentality of design was for secretbox to be silent and swallow errors
over raising during run-time. It was expected that missing values or
failures would, eventually, cause an error.
The new approach will focus on a fail-fast approach.
SecretBox objects will hold a `dict[str, str]`. Optionally this
can be pre-loaded with the existing environment variables from
`os.environ`.
The SecretBox object should behave, within reason, as a dictionary. Due
to opinion, all keys in the SecretBox store will be normilized to
uppercase.
Support for `__getitem__` and `__setitem__` added.
=> Strip down secretbox.py for 3.0

src/secretbox/secretbox.py, tests/secretbox_test.py
After consideration of #160, the loading of environment variables should be handled exclusively in a loader. This is kicking the can on how to handle `os.environ` behavior when in a Windows OS. However, it makes sense that the SecretBox instance should be case sensitive with keys. It is patterned to behave like a dictionary. Changing the behavior of `__setitem__` and `__getitem__` here would be more surprising to a dev than not.
=> Remove auto-load of environment variables

src/secretbox/secretbox.py, tests/secretbox_test.py
This method behaves close to the dictionary .get() method with two exceptions. The `default` value, if provided, must be a string. If the `default` value is omitted and the `key` does not exist then a `KeyError` will be raised.
=> Implement the .get() method

src/secretbox/secretbox.py, tests/secretbox_test.py
This method attempts to return the requested value as an integer instead of a string. Exceptions are raised if the convertion fails. All other behavior mirrors `.get()`.
There is the question of what to do with floats here. If the value is a float it will successfully be converted to an int. However, that changes the value. We should likely raise an exception in this case.
=> Implement .get_int() method

src/secretbox/secretbox.py, tests/secretbox_test.py
If the `default` arguement is not the correct type, raise a TypeError.
=> Raise TypeError instead of ValueError

src/secretbox/secretbox.py, tests/secretbox_test.py
This is a non-issue for `get_int()`. A string representing a float will raise a ValueError with `int()`.
=> Address TODO

src/secretbox/secretbox.py, tests/secretbox_test.py
This method will attempt to return the requested value as a float. For the case of "42", Python will coerce the type to a float. This, however, changes the defined value of 42 to 42.0. In this case the method will raise a ValueError.
=> Implement .get_float()

src/secretbox/secretbox.py
Any valid `.isdigit()` should fail the `get_float()` request. This will cover "42" which should not be coerced into a float. It will also cover "\u0082" which is a valid digit but also an invalid int and float.
=> Clean up nesting for int check

src/secretbox/secretbox.py, tests/secretbox_test.py
During assignment or load() actions, if a key already exists then raise a KeyError by default. This is to prevent the clobbering of existing key:value pairs in the SecretBox.
This behavior can be disabled with the `raise_on_overwrite` keyword parameter during initialization. This behavior should not be changed once the SecretBox is initialized.
=> Implement strict behavior on key assignment
